# Site settings
title: Maptime Detroit
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    Maptime's mission is to open the doors of cartographic possibility to anyone 
    interested by creating a time and space for collaborative learning, exploration, 
    and map creation using mapping tools and technologies.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://maptimedet.github.io" # the base hostname & protocol for your site
twitter_username: maptimedetroit
github_username:  maptimedet

# Build settings
markdown: kramdown
